# Motion-comic timeline from comic.json + recorded lines -> src/timeline.json (route "comic"; never edit by hand).
# Camera rules: a line starts 0.65 s after the camera arrives on its panel, lines in one panel are 0.28 s apart,
# panels without lines pass in 0.72 s; page transitions turn / slide / push / flash; a clip mapped to a panel is
# pasted back at its crop box (the camera pushes to that box = full screen); "shake" lines jolt the frame;
# panels listed in "knocks" pop their sound-effect lettering twice.
# comic.json: {title, chapter, subtitle, names{role: [label, color]}, pages[{id, image, size, trans?, panels[{id, box, read_order,
#   lettering[{kind, rect}]}]}], lines[{id, panel, role, plain, en, shake?}], captions[{panel, role, plain, en}],
#   clips{panel_id: {id, box, hold?}}, knocks[panel_id]}
# usage: python tools/plan_comic.py <project>
from kit import project, rj, wj, speech, probe_dur

FPS = 24
ARRIVE, GAP, PASS, TRAVEL, HOLD, END = 0.65, 0.28, 0.72, 0.55, 0.55, 4.0
TIN = {'open': 0.0, 'turn': 1.1, 'slide': 0.8, 'push': 0.9, 'flash': 0.35}

name, ROOT = project()
C = rj(ROOT / 'comic.json')
by_panel, caps = {}, {}
for l in C['lines']:
    by_panel.setdefault(l['panel'], []).append(l)
for l in C.get('captions', []):
    caps.setdefault(l['panel'], []).append(l)


def clipdur(cid):
    p = ROOT / f'assets/video/{cid}.mp4'
    return probe_dur(p) if p.exists() else 5.0


t = 0.0
pages, panels, lines, subs, fx, clips = [], [], [], [], [], []
first = C['pages'][0]['panels'][0]['id'] if C['pages'] else None
opener = C.get('clips', {}).get(first)
OPEN = clipdur(opener['id']) if opener else 0.0   # an opener clip on the first panel plays full screen before the title lands
for pi, pg in enumerate(C['pages']):
    tr = 'open' if pi == 0 else pg.get('trans', 'turn')
    p0 = t
    t += TIN[tr]
    for pn in sorted(pg['panels'], key=lambda x: x['read_order']):
        a = t
        is_first = pn['id'] == first
        arrive = a + (0 if is_first else TRAVEL)
        own = by_panel.get(pn['id'], [])
        cur = OPEN - 0.4 if is_first and opener else arrive + ARRIVE
        for j, l in enumerate(own):
            if j:
                cur += GAP
            lead, d = speech(ROOT / f"assets/voice/lines/{l['id']}.mp3")
            lines.append({'id': l['id'], 'panel': pn['id'], 'who': l['role'], 'at': round(cur, 3), 'len': round(d, 3), 'lead': round(lead, 3)})
            subs.append([round(cur - 0.05, 2), round(cur + d + 0.35, 2), l['plain'], l['role'], l['en']])
            if l.get('shake'):
                fx.append({'kind': 'shake', 't': round(cur, 3)})
            cur += d
        end = cur + HOLD if own else arrive + PASS
        for k in caps.get(pn['id'], []):   # narration / sfx captions: translation only, no extra time
            st = OPEN + 0.2 if is_first and opener else arrive + 0.3
            subs.append([round(st, 2), round(max(end, st + 1.6), 2), k['plain'], k['role'], k['en']])
        if pn['id'] in C.get('knocks', []):
            r = next(x for x in pn['lettering'] if x['kind'] == 'sfx')['rect']   # panel space -> page space
            fx.append({'kind': 'knock', 't': round(arrive + 0.15, 3), 'panel': pn['id'], 'rect': [pn['box'][0] + r[0], pn['box'][1] + r[1], r[2], r[3]]})
        c = C.get('clips', {}).get(pn['id'])
        if c:
            cd = clipdur(c['id'])
            if is_first:
                c0 = 0.0; end = max(end, OPEN + 1.6)
            else:
                c0 = arrive + 0.35; end = max(end, c0 + cd + 0.4)
            clips.append({'id': c['id'], 'panel': pn['id'], 'page': pg['id'], 'box': c['box'], 't0': round(c0, 3), 't1': round(min(c0 + cd, end - 0.2), 3), 'len': round(cd, 3), 'hold': bool(c.get('hold'))})
        panels.append({'id': pn['id'], 'page': pg['id'], 'box': pn['box'], 'a': round(a, 3), 'arrive': round(arrive, 3), 'end': round(end, 3)})
        t = end
    pages.append({'id': pg['id'], 'image': pg['image'], 'size': pg['size'], 't0': round(p0, 3), 't1': round(t, 3), 'trans': tr, 'tin': TIN[tr]})
t += 0.6
names = C.get('names', {})
for a, b in zip(subs, subs[1:]):
    if a[3] in names and b[3] in names:
        a[1] = min(a[1], b[0] - 0.02)
dur = round(t + END, 2)
wj(ROOT / 'src/timeline.json', {'_note': 'generated by tools/plan_comic.py, do not edit', 'route': 'comic', 'fps': FPS, 'dur': dur, 'end': round(t, 3),
                                'title': C.get('title', ''), 'chapter': C.get('chapter', ''), 'subtitle': C.get('subtitle', ''), 'names': names,
                                'holds': [[round(t - 2.0, 2), dur]],   # the end-title hold is by design (verify.py)
                                'pages': pages, 'panels': panels, 'lines': lines, 'subs': subs, 'fx': fx, 'clips': clips})
print(name, 'dur', dur, 's |', len(pages), 'pages', len(panels), 'panels', len(lines), 'lines', len(clips), 'clips', len(fx), 'fx')
