# Timeline from board + recorded voice: projects/<p>/src/timeline.json is the only source of time (never edit it by hand).
# Sections follow board.json order; each waits `lead` s, lines are separated by a gap (shorter when the speaker changes),
# `pre` adds a pause before line k, `tail` ends the section. Long Japanese lines are split into subtitle chunks
# (≤ MAXC chars, cut at 。！？ then 、) and each chunk gets a share of the line's time by character count.
# usage: python tools/plan.py <project>
import re
import numpy as np
from kit import project, rj, wj, speech

FPS = 24
GAP_SAME, GAP_SWAP = 0.5, 0.3
MAXC = 30


def chunks(s):
    out = []
    for p in [p for p in re.split(r'(?<=[。！？])', s) if p]:
        while len(p) > MAXC:
            cut = max((m.end() for m in re.finditer('、', p[:MAXC + 1])), default=0) or MAXC
            out.append(p[:cut]); p = p[cut:]
        if p:
            out.append(p)
    merged = []
    for p in out:   # fold very short chunks into the previous one
        if merged and len(p) < 7 and len(merged[-1]) + len(p) <= MAXC + 6:
            merged[-1] += p
        else:
            merged.append(p)
    return merged


name, ROOT = project()
board = rj(ROOT / 'src/board.json')
script = rj(ROOT / 'assets/voice/script.json')['lines']
t, secs, lines, subs = 0.6, {}, [], []
prev_who = None
for sec in board['secs']:
    s = sec['id']
    own = [l for l in script if l['sec'] == s]
    t0 = t
    t += sec.get('lead', 0.6)
    for k, l in enumerate(own):
        if k:
            t += GAP_SAME if l['voice'] == prev_who else GAP_SWAP
        t += sec.get('pre', {}).get(str(k), 0)
        lead, dur = speech(ROOT / f"assets/voice/lines/{l['id']}.mp3")
        lines.append({'id': l['id'], 'sec': s, 'k': k, 'who': l['voice'], 'at': round(t, 3), 'lead': round(lead, 3), 'len': round(dur, 3), **({'en': l['en']} if l.get('en') else {})})
        if l.get('parts'):   # explicit cut points in the script: one Japanese chunk per English chunk
            parts, ens = [a for a, _ in l['parts']], [b for _, b in l['parts']]
        elif l.get('en'):   # pair sentence by sentence; if the counts differ, one block
            jp = [p.strip('　 ') for p in re.split(r'(?<=[。！？])', l['plain']) if p.strip('　 ')]
            en = [p for p in re.split(r'(?<=[.!?])\s+(?=\S)', l['en'].strip()) if p]
            parts, ens = (jp, en) if len(jp) == len(en) else ([l['plain']], [l['en']])
        else:
            parts = [p.strip('　 ') for p in chunks(l['plain'])]; ens = [None] * len(parts)
        w = np.array([max(5, len(p)) for p in parts], float)
        cut = np.concatenate([[0], np.cumsum(w) / w.sum()]) * dur
        for i, p in enumerate(parts):
            subs.append([round(t + cut[i] - 0.05, 2), round(t + cut[i + 1] + (0.4 if i == len(parts) - 1 else 0.02), 2), p, l['voice'], *([ens[i]] if ens[i] else [])])
        t += dur
        prev_who = l['voice']
    t += sec.get('tail', 1.0)
    secs[s] = [round(t0, 3), round(t, 3)]
for a, b in zip(subs, subs[1:]):
    a[1] = min(a[1], b[0] - 0.02)
dur = round(t + 0.6, 2)
wj(ROOT / 'src/timeline.json', {'_note': 'generated by tools/plan.py, do not edit', 'fps': FPS, 'dur': dur, 'secs': secs, 'lines': lines, 'subs': subs,
                                'holds': board.get('holds', [])})
print(name, 'dur', dur, 's,', len(lines), 'lines,', len(subs), 'subs')
for s, (a, b) in secs.items():
    print(f'  {s:10s} {a:7.1f} {b - a:6.1f}')
